
#include<dos.h>
#include<graphics.h>
#include<stdio.h>
#include<conio.h>

//Auto fuction
 void Auto()
      {
	int c,d,e,f;
	 int f3=175,g3=196,a3=220,b3=247,c4=262,d4=294,e4=330,f4=350,g4=392,a4=440,b4=494;
	int  c3=131,d3=147,e3=165,a2=100,e2=83,d2=74,f33=185,g33=208,c44=277,c33=139;
      printf("select the song\n ");
      printf("1.saa ree ga ma pa dha ni \n 2.Happy birthday \n 3.twinkil little star \n 4.Nokia\n ");
      scanf("%d",&c);
      if (c==1)
       {

	sound(240);
	delay(400);
	nosound();

	sound(270);
	delay(400);
	nosound();

	sound(300);
	delay(400);
	nosound();

	sound(320);
	delay(400);
	nosound();

	sound(360);
	delay(400);
	nosound();

	sound(400);
	delay(400);
	nosound();

	sound(450);
	delay(400);
	nosound();

	sound(240);
	delay(400);
	nosound();

	sound(450);
	delay(400);
	nosound();

	sound(400);
	delay(400);
	nosound();

	sound(360);
	delay(400);
	nosound();

	sound(320);
	delay(400);
	nosound();

	sound(300);
	delay(400);
	nosound();

	sound(270);
	delay(400);
	nosound();

	sound(240);
	delay(400);
	nosound();

	}

	else if (c==2){


	sound(g3);
	      delay(300);
	      nosound();

	 sound(g3);
	      delay(300);
	      nosound();

	 sound(a3);
	      delay(600);
	      nosound();

	 sound(g3);
	      delay(600);
	      nosound();

	 sound(c4);
	      delay(600);
	      nosound();

	 sound(b3);
	      delay(1200);
	      nosound();

	 sound(g3);
	      delay(300);
	      nosound();

	 sound(g3);
	      delay(300);
	      nosound();

	 sound(a3);
	      delay(600);
	      nosound();

	 sound(g3);
	      delay(600);
	      nosound();

	 sound(d4);
	      delay(600);
	      nosound();

	 sound(c4);
	      delay(1200);
	      nosound();

	 sound(g3);
	      delay(300);
	      nosound();

	 sound(g3);
	      delay(300);
	      nosound();

	 sound(g4);
	      delay(300);
	      nosound();

	 sound(e4);
	      delay(600);
	      nosound();

	 sound(c4);
	      delay(600);
	      nosound();

	 sound(b3);
	      delay(600);
	      nosound();

	 sound(a3);
	      delay(900);
	      nosound();

	 sound(f4);
	      delay(300);
	      nosound();

	 sound(f4);
	      delay(300);
	      nosound();

	 sound(e4);
	      delay(600);
	      nosound();

	 sound(c4);
	      delay(600);
	      nosound();

	 sound(d4);
	      delay(600);
	      nosound();

	 sound(c4);
	      delay(1200);
	      nosound(); }

	      else if(c==3){

	 sound(g3);
	      delay(200);
	      nosound();
	      delay(200);

	 sound(g3);
	      delay(200);
	      nosound();
	      delay(400);
	 sound(d4);
	      delay(200);
	      nosound();
	      delay(200);

	 sound(d4);
	      delay(400);
	      nosound();
	 sound(e4);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(e4);
	      delay(400);
	      nosound();

	 sound(d4);
	      delay(800);
	      nosound();
	 sound(c4);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(c4);
	      delay(400);
	      nosound();
	 sound(b3);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(b3);
	      delay(400);
	      nosound();
	 sound(a3);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(a3);
	      delay(400);
	      nosound();
	 sound(g3);
	      delay(800);
	      nosound();
	for(f=0;f<2;f++){
	sound(c4);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(c4);
	      delay(400);
	      nosound();
	 sound(b3);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(b3);
	      delay(400);
	      nosound();

	 sound(a3);
	      delay(800);
	     nosound();

	 sound(g3);
	      delay(200);
	      nosound();
	      delay(200);

	 sound(g3);
	      delay(200);
	      nosound();
	      delay(400);
	 sound(d4);
	      delay(200);
	      nosound();
	      delay(200);

	 sound(d4);
	      delay(400);
	      nosound();
	 sound(e4);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(e4);
	      delay(400);
	      nosound();

	 sound(d4);
	      delay(800);
	      nosound();
	 sound(c4);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(c4);
	      delay(400);
	      nosound();
	 sound(b3);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(b3);
	      delay(400);
	      nosound();
	 sound(a3);
	      delay(200);
	      nosound();
	      delay(200);
	 sound(a3);
	      delay(400);
	      nosound();


	 sound(g3);
	      delay(800);
	      nosound();
	     }


	      }
	      else if (c==4){
	      for(e=0;e<2;e++){
	       sound(e4);
	      delay(300);
	      nosound();
	       sound(d4);
	      delay(300);
	      nosound();
	       sound(f33);
	      delay(600);
	      nosound();
	       sound(g33);
	      delay(600);
	      nosound();
	      sound(d4);
	      delay(300);
	      nosound();
	       sound(c44);
	      delay(300);
	      nosound();
	       sound(b3);
	      delay(300);
	      nosound();
	       sound(d3);
	      delay(600);
	      nosound();
	       sound(e3);
	      delay(600);
	      nosound();
	       sound(b3);
	      delay(300);
	      nosound();
	       sound(a3);
	      delay(300);
	      nosound();
	       sound(c33);
	      delay(600);
	      nosound();
	       sound(e3);
	      delay(600);
	      nosound();
	      sound(a3);
	      delay(3600);
	      nosound();

		}

	      }
	      else{
	      printf("enter correct option");
	      }




}

// Manual fuction
    void manual()
      {
	int b,y,z;
	int f3=175,g3=196,a3=220,b3=247,c4=262,d4=294,e4=330,f4=350,g4=392,a4=440,b4=494;
	int  c3=131,d3=147,e3=165,a2=100,e2=83,d2=74,f33=185,g33=208,c44=277,c33=139;
	 printf(" 1.f3 \n 2.g3 \n 3.a3 \n 4.n3 \n 5.c4 \n 6.d4 \n 7.e4 \n 8.f4 \n 9.g4 \n 10.a4 \n 11.b4 \n 12.c3 \n 13.d3 \n 14.e3 \n 15.a2\n 16.e2 \n 17.d2 \n 18.f33 \n 19.g33 \n 20.c44 \n 21.c33 \n");
	 printf("enter the chord no to play\n");
	printf("This guitar plays only one time ( chord_key)\n");
	 scanf("%d",&b);

      //	 for(y=0;y<x;y++){
	// printf("enter the chord number to play\n");


	// scanf("%d",&z);
       /*	 sound(z);
	 delay(500);
	 nosound();
		 }*/
	     if(b==1)  {
	      sound(175);
	      delay(500);
	      nosound();
	      }
	    else if (b==2) { sound(196);
	     delay(500);
	      nosound();
	      }
	      else if(b==3) {  sound(220);
	       delay(500);
	      nosound();
	      }
		 else if(b==4){ sound(247);
		  delay(500);
	      nosound();
	      }
		    else if(b==5){ sound(262);
		     delay(500);
	      nosound();
	      }
		       else if(b==6){ sound(294);
			delay(500);
	      nosound();
	      }
			  else if(b==7){ sound(330);
			   delay(500);
	      nosound();
	      }
			     else if(b==8){ sound(350);
			      delay(500);
	      nosound();
	      }
				else if(b==9){ sound(392);
				 delay(500);
	      nosound();
	      }
				   else if(b==10){ sound(440);
				    delay(500);
	      nosound();
	      }
				      else if(b==11){ sound(494);
				       delay(500);
	      nosound();
	      }
		 else if(b==12){ sound(131);
		  delay(500);
	      nosound();
	      }
		    else if(b==13){ sound(147);
		     delay(500);
	      nosound();
	      }
		       else if(b==14){ sound(165);
			delay(500);
	      nosound();
	      }
			  else if(b==15){ sound(100);
			   delay(500);
	      nosound();
	      }
			     else if(b==16){ sound(83);
			      delay(500);
	      nosound();
	      }
				else if(b==17){ sound(74);
				 delay(500);
	      nosound();
	      }
				   else if(b==18){ sound(185);
				    delay(500);
	      nosound();
	      }
				      else if(b==19){ sound(208);
				       delay(500);
	      nosound();
	      }
					 else if(b==20){ sound(277);
					  delay(500);
	      nosound();
	      }
					    else if(b==21){ sound(139);
	      delay(500);
	      nosound();
	      }

	      else {
	      printf("incorrect chord \n");
		}
     }

    //Main function

       void main()
	{
    int gdriver = DETECT, gmode,i,j,k,l,m,n,o,p,q,a;
    clrscr();

    initgraph(&gdriver, &gmode, "c:\\turboc3\\bgi");
     setbkcolor(YELLOW);
     setcolor(RED);
     settextstyle(1,0,7);
     outtextxy(50,150," VIRTUAL GUITAR ");
     delay(4000);
     setcolor(BLUE);
      settextstyle(1,0,2);
     outtextxy(200,400,"(with_C_graphics)");
   delay(5000);
     clrscr();


    setbkcolor(WHITE);
     setbkcolor(BLACK);

    setcolor(WHITE);
    settextstyle(1,0,2);
    outtextxy(150,100," Close view of guitar (Virtual)");
    rectangle(0,200,600,300);


    setcolor(MAGENTA);
      circle(525,250,50);

    setcolor(RED);
    for(i=12.5;i<80;i+=12.5)
    {
    line(1,200+i,599,200+i);
    }
    setcolor(BLUE);
    for(j=150;j<400;j+=150){
    line(1+j,200,1+j,300);
    }
    for(k=50;k<150;k+=50){
    line(0+k,200,0+k,300);
    }
    for(l=25;l<150;l+=25){
    line(150+l,200,150+l,300);
	 }
    for(m=12.5;m<140;m+=12.5){
    line(300+m,200,300+m,300);
      }

    setcolor(YELLOW);
       settextstyle(0,0,1);
       outtextxy(25,190,"1");
       outtextxy(75,190,"2");
       outtextxy(125,190,"3");
       outtextxy(162.5,190,"4");
       outtextxy(162.5,190,"4");
	  outtextxy(187.5,190,"5");
	     outtextxy(212.5,190,"6");
	       outtextxy(237.5,190,"7");
	       outtextxy(262.5,190,"8");
	      outtextxy(287.5,190,"9");
	//      outtextxy(306.25,190,"10");
	       outtextxy(312.5,190,"11");
	  //	outtextxy(318.75,190,"12");
	    outtextxy(335,190,"13");
	      //	 outtextxy(331.25,190,"14");
		 outtextxy(359.5,190,"15");
		//  outtextxy(343.75,190,"16");
		   outtextxy(385,190,"17");
		    //outtextxy(356.25,190,"18");
		     outtextxy(405.5,190,"19");
		      outtextxy(420.5,190,"20");
		     outtextxy(610,212.5,"e4");
		      outtextxy(610.5,225,"b3");
		       outtextxy(610.5,237.5,"g3");
			outtextxy(610.5,250,"d3");
			outtextxy(610.5,263.2,"a2");
			outtextxy(610.5,275.6,"e2");


			delay(7000);
			getch();
			clrscr();





		setbkcolor(WHITE);
		setcolor(RED);
		settextstyle(3,0,2);
		outtextxy(10,10,"Select your choice");
		setcolor(MAGENTA);
		settextstyle(1,0,5);
		outtextxy(50,150," 1. Manual mode ");
		outtextxy(50,200," 2. Auto mode");
		delay(4000);
		getch();
		clrscr;
		 closegraph();




	   printf("enter your choice\n");
	   scanf("%d",&a);
	   if(a==1){
	   manual(); }
	   else if (a==2) {
	   Auto(); }
	   else{
	   printf("enter correct choice");
	   }


  }




